spring.application.name=query-report-api-service
spring.main.web-application-type=none
spring.main.banner-mode=off
forensics.query-report-api.service.http.enabled=true
forensics.query-report-api.service.http.host=127.0.0.1
forensics.query-report-api.service.http.port=0
forensics.query-report-api.service.analysis-orchestrator.grpc.host=127.0.0.1
forensics.query-report-api.service.analysis-orchestrator.grpc.port=0
forensics.query-report-api.service.analysis-orchestrator.grpc.deadline-seconds=1
