spring.application.name=forensic-gateway-service
spring.main.web-application-type=none
spring.main.banner-mode=off
forensics.gateway.service.http.enabled=true
forensics.gateway.service.http.host=0.0.0.0
forensics.gateway.service.http.port=8080
