spring.application.name=forensic-gateway-service
spring.main.web-application-type=none
spring.main.banner-mode=off
forensics.gateway.service.http.enabled=true
forensics.gateway.service.http.host=127.0.0.1
forensics.gateway.service.http.port=8080
forensics.gateway.service.analysis-store.grpc.host=127.0.0.1
forensics.gateway.service.analysis-store.grpc.port=9091
forensics.gateway.service.analysis-store.grpc.deadline-seconds=5
