spring.application.name=forensic-gateway-service
spring.main.web-application-type=none
spring.main.banner-mode=off
forensics.gateway.service.http.enabled=true
forensics.gateway.service.http.host=127.0.0.1
forensics.gateway.service.http.port=0
forensics.gateway.service.repository-analysis.grpc.host=127.0.0.1
forensics.gateway.service.repository-analysis.grpc.port=0
forensics.gateway.service.repository-analysis.grpc.deadline-seconds=1
