forensics.java-parser-analysis.service.grpc.host=0.0.0.0
forensics.java-parser-analysis.service.grpc.port=9094
forensics.java-parser-analysis.service.health.host=0.0.0.0
forensics.java-parser-analysis.service.health.port=8085
forensics.java-parser-analysis.service.artifacts.root=/var/lib/forensic-analytics/java-parser-analysis-artifacts
