spring.main.web-application-type=none
spring.main.banner-mode=off
forensics.java-parser-analysis.service.grpc.enabled=true
forensics.java-parser-analysis.service.grpc.host=127.0.0.1
forensics.java-parser-analysis.service.grpc.port=9094
forensics.java-parser-analysis.service.health.enabled=true
forensics.java-parser-analysis.service.health.host=127.0.0.1
forensics.java-parser-analysis.service.health.port=8085
forensics.java-parser-analysis.service.artifacts.root=build/java-parser-analysis-artifacts
