forensics.java-parser-analysis.service.grpc.port=0
forensics.java-parser-analysis.service.health.port=0
forensics.java-parser-analysis.service.artifacts.root=build/test-java-parser-analysis-artifacts
