spring.main.banner-mode=off
spring.main.web-application-type=none

forensics.joern-cpg-analysis.service.grpc.enabled=true
forensics.joern-cpg-analysis.service.grpc.host=0.0.0.0
forensics.joern-cpg-analysis.service.grpc.port=9094
forensics.joern-cpg-analysis.service.health.enabled=true
forensics.joern-cpg-analysis.service.health.host=0.0.0.0
forensics.joern-cpg-analysis.service.health.port=8085
forensics.joern-cpg-analysis.service.workspace.root=build/joern-cpg-workspaces
forensics.joern-cpg-analysis.service.artifacts.root=build/joern-cpg-artifacts
forensics.joern-cpg-analysis.service.joern.executable=joern
forensics.joern-cpg-analysis.service.joern.parse-executable=joern-parse
forensics.joern-cpg-analysis.service.joern.heap=8G
forensics.joern-cpg-analysis.service.joern.query-scripts-root=/opt/forensic-analytics/joern-cpg-analysis/queries
forensics.joern-cpg-analysis.service.joern.runtime-image-reference=ghcr.io/joernio/joern@sha256:7918dc450f185433fe6cfaf43e86f5daf5643fba2139406a41a1e6e1d6134295
