forensics.joern-cpg-analysis.service.workspace.root=/var/lib/forensic-analytics/joern-cpg-workspaces
forensics.joern-cpg-analysis.service.artifacts.root=/var/lib/forensic-analytics/joern-cpg-artifacts
forensics.joern-cpg-analysis.service.joern.query-scripts-root=/opt/forensic-analytics/joern-cpg-analysis/queries
forensics.joern-cpg-analysis.service.joern.runtime-image-reference=ghcr.io/joernio/joern@sha256:7918dc450f185433fe6cfaf43e86f5daf5643fba2139406a41a1e6e1d6134295
