forensics.joern-analysis.service.workspace.root=/var/lib/forensic-analytics/joern-analysis-workspaces
forensics.joern-analysis.service.artifacts.root=/var/lib/forensic-analytics/joern-analysis-artifacts
forensics.joern-analysis.service.analysis-store.host=analysis-store-service
forensics.joern-analysis.service.analysis-store.port=9091
forensics.joern-analysis.service.analysis-store.deadline-seconds=5
forensics.joern-analysis.service.joern.query-scripts-root=/opt/forensic-analytics/joern-analysis/queries
forensics.joern-analysis.service.joern.runtime-image-reference=ghcr.io/joernio/joern@sha256:7918dc450f185433fe6cfaf43e86f5daf5643fba2139406a41a1e6e1d6134295
