forensics.joern-analysis.service.grpc.port=0
forensics.joern-analysis.service.health.port=0
forensics.joern-analysis.service.workspace.root=build/test-joern-analysis-workspaces
forensics.joern-analysis.service.artifacts.root=build/test-joern-analysis-artifacts
