spring.application.name=forensic-ingestion-service
spring.main.web-application-type=none
forensics.ingestion.service.grpc.enabled=true
forensics.ingestion.service.grpc.host=127.0.0.1
forensics.ingestion.service.grpc.port=9090
forensics.ingestion.service.health.enabled=true
forensics.ingestion.service.health.host=127.0.0.1
forensics.ingestion.service.health.port=8081
