forensics.analysis-store.service.grpc.host=0.0.0.0
forensics.analysis-store.service.grpc.port=9091
forensics.analysis-store.service.health.host=0.0.0.0
forensics.analysis-store.service.health.port=8082
forensics.analysis-store.service.java-ast-analysis.grpc.host=java-ast-analysis-service
forensics.analysis-store.service.java-ast-analysis.grpc.port=9093
forensics.analysis-store.service.java-ast-analysis.grpc.deadline-seconds=30
forensics.analysis-store.service.java-ast-analysis.grpc.max-bytes=104857600
