spring.main.web-application-type=none
spring.main.banner-mode=off
forensics.analysis-store.service.grpc.enabled=true
forensics.analysis-store.service.grpc.host=127.0.0.1
forensics.analysis-store.service.grpc.port=9091
forensics.analysis-store.service.health.enabled=true
forensics.analysis-store.service.health.host=127.0.0.1
forensics.analysis-store.service.health.port=8082
