forensics.analysis-store.service.grpc.host=0.0.0.0
forensics.analysis-store.service.grpc.port=9091
forensics.analysis-store.service.health.host=0.0.0.0
forensics.analysis-store.service.health.port=8082
forensics.analysis-store.service.java-ast-analysis.grpc.host=java-ast-analysis-service
forensics.analysis-store.service.java-ast-analysis.grpc.port=9093
forensics.analysis-store.service.java-ast-analysis.grpc.deadline-seconds=30
forensics.analysis-store.service.java-ast-analysis.grpc.max-bytes=104857600
forensics.analysis-store.service.repository-analysis.grpc.host=repository-analysis-service
forensics.analysis-store.service.repository-analysis.grpc.port=9092
forensics.analysis-store.service.repository-analysis.grpc.deadline-seconds=30
forensics.analysis-store.service.joern-cpg-analysis.grpc.host=joern-cpg-analysis-service
forensics.analysis-store.service.joern-cpg-analysis.grpc.port=9094
forensics.analysis-store.service.joern-cpg-analysis.grpc.deadline-seconds=30
forensics.analysis-store.service.joern-cpg-analysis.grpc.joern-image-reference=ghcr.io/joernio/joern@sha256:7918dc450f185433fe6cfaf43e86f5daf5643fba2139406a41a1e6e1d6134295
forensics.analysis-store.service.joern-cpg-analysis.grpc.query-bundle-version=analysis-store-default-v1
forensics.analysis-store.service.btm-generation.grpc.host=btm-generation-service
forensics.analysis-store.service.btm-generation.grpc.port=9095
forensics.analysis-store.service.btm-generation.grpc.deadline-seconds=30
forensics.analysis-store.service.btm-generation.grpc.max-artifact-bytes=104857600
