forensics.analysis-store.service.grpc.host=0.0.0.0
forensics.analysis-store.service.grpc.port=9091
forensics.analysis-store.service.health.host=0.0.0.0
forensics.analysis-store.service.health.port=8082
