spring.main.web-application-type=none
spring.main.banner-mode=off
forensics.analysis-store.service.grpc.enabled=true
forensics.analysis-store.service.grpc.host=127.0.0.1
forensics.analysis-store.service.grpc.port=9091
forensics.analysis-store.service.health.enabled=true
forensics.analysis-store.service.health.host=127.0.0.1
forensics.analysis-store.service.health.port=8082
forensics.analysis-store.service.java-ast-analysis.grpc.host=127.0.0.1
forensics.analysis-store.service.java-ast-analysis.grpc.port=9093
forensics.analysis-store.service.java-ast-analysis.grpc.deadline-seconds=30
forensics.analysis-store.service.java-ast-analysis.grpc.max-bytes=104857600
