spring.main.web-application-type=none
spring.main.banner-mode=off
forensics.analysis-orchestrator.service.grpc.enabled=true
forensics.analysis-orchestrator.service.grpc.host=127.0.0.1
forensics.analysis-orchestrator.service.grpc.port=9098
forensics.analysis-orchestrator.service.health.enabled=true
forensics.analysis-orchestrator.service.health.host=127.0.0.1
forensics.analysis-orchestrator.service.health.port=8089
