forensics.java-ast-analysis.service.grpc.host=0.0.0.0
forensics.java-ast-analysis.service.grpc.port=9093
forensics.java-ast-analysis.service.health.host=0.0.0.0
forensics.java-ast-analysis.service.health.port=8084
forensics.java-ast-analysis.service.artifacts.root=/var/lib/forensic-analytics/java-ast-artifacts
