spring.main.web-application-type=none
spring.main.banner-mode=off
forensics.java-ast-analysis.service.grpc.enabled=true
forensics.java-ast-analysis.service.grpc.host=127.0.0.1
forensics.java-ast-analysis.service.grpc.port=9093
forensics.java-ast-analysis.service.health.enabled=true
forensics.java-ast-analysis.service.health.host=127.0.0.1
forensics.java-ast-analysis.service.health.port=8084
forensics.java-ast-analysis.service.artifacts.root=build/java-ast-analysis-artifacts
