forensics.repository-analysis.service.grpc.enabled=true
forensics.repository-analysis.service.grpc.host=127.0.0.1
forensics.repository-analysis.service.grpc.port=9092
forensics.repository-analysis.service.health.enabled=true
forensics.repository-analysis.service.health.host=127.0.0.1
forensics.repository-analysis.service.health.port=8083
forensics.repository-analysis.service.workspace.root=build/repository-analysis-workspaces
