forensics.repository-source.service.grpc.enabled=true
forensics.repository-source.service.grpc.host=127.0.0.1
forensics.repository-source.service.grpc.port=9092
forensics.repository-source.service.health.enabled=true
forensics.repository-source.service.health.host=127.0.0.1
forensics.repository-source.service.health.port=8083
forensics.repository-source.service.workspace.root=build/repository-source-workspaces
forensics.repository-source.service.persistence.type=h2
forensics.repository-source.service.persistence.h2.jdbc-url=jdbc:h2:file:build/repository-source-data/repository-source;AUTO_SERVER=FALSE;DB_CLOSE_DELAY=-1
forensics.repository-source.service.persistence.h2.username=sa
forensics.repository-source.service.persistence.h2.password=
