forensics.repository-source.service.grpc.enabled=true
forensics.repository-source.service.grpc.host=127.0.0.1
forensics.repository-source.service.grpc.port=0
forensics.repository-source.service.health.enabled=true
forensics.repository-source.service.health.host=127.0.0.1
forensics.repository-source.service.health.port=0
forensics.repository-source.service.workspace.root=build/repository-source-test-workspaces
