forensics.joern-cpg-analysis.service.grpc.port=0
forensics.joern-cpg-analysis.service.health.port=0
forensics.joern-cpg-analysis.service.workspace.root=build/test-joern-cpg-workspaces
forensics.joern-cpg-analysis.service.artifacts.root=build/test-joern-cpg-artifacts
