forensics.analytics.workspace.root-path=./build/forensic-analytics-test
forensics.analytics.workspace.base-path=./build/forensic-analytics-test/workspaces
forensics.analytics.workspace.allow-relative-paths=true
forensics.analytics.ingestion.grpc.enabled=false
forensics.analytics.rest.enabled=false
forensics.analytics.joern.output-directory=./build/forensic-analytics-test/workspaces/joern
