forensics.analytics.workspace.root-path=./build
forensics.analytics.workspace.base-path=./build/test-workspaces
forensics.analytics.workspace.allow-relative-paths=true
forensics.analytics.ingestion.grpc.enabled=false
forensics.analytics.rest.enabled=false
forensics.analytics.joern.output-directory=./build/test-workspaces/joern
