forensics.btm-generation.service.grpc.host=127.0.0.1
forensics.btm-generation.service.grpc.port=0
forensics.btm-generation.service.health.host=127.0.0.1
forensics.btm-generation.service.health.port=0
forensics.btm-generation.service.artifacts.root=build/test-btm-generation-artifacts
