spring.application.name=btm-generation-service
spring.main.web-application-type=none
spring.main.banner-mode=off
forensics.btm-generation.service.grpc.enabled=true
forensics.btm-generation.service.grpc.host=127.0.0.1
forensics.btm-generation.service.grpc.port=9095
forensics.btm-generation.service.health.enabled=true
forensics.btm-generation.service.health.host=127.0.0.1
forensics.btm-generation.service.health.port=8086
forensics.btm-generation.service.artifacts.root=build/btm-generation-artifacts
forensics.btm-generation.service.generator.version=btm-generation-service-0.1.0
